name: Keep Railway DB Awake

on:
    schedule:
        - cron: "*/5 * * * *" # runs every 10 minutes
    workflow_dispatch: # lets you manually trigger it too

jobs:
    ping-db:
        runs-on: ubuntu-latest

        steps:
            - name: Ping backend URL
              env:
                  BACKEND_URL: ${{ secrets.BACKEND_URL }}
              run: |
                  echo "Pinging backend..."
                  curl -I --silent --show-error --max-time 10 "$BACKEND_URL" || echo "⚠️ Backend ping failed"
                  echo "✅ Backend ping done."
